### ISSUE TITLE
spaCy 3.5 Support

### ISSUE THREAD

**Issue by Dris101** [KennethEnevoldsen/spacy-wrap#106]
Hi Kenneth,
Any chance of bumping the spaCy dependency to <3.6? Poetry won't resolve my dependencies against spaCy 3.5.0 at present
```
Because spacy-wrap (1.4.0) depends on spacy (>=3.2.1,<3.5.0)
 and no versions of spacy-wrap match >1.4,<2.0, spacy-wrap (>=1.4,<2.0) requires spacy (>=3.2.1,<3.5.0).
```
not sure if that is as simple as bumping the version number on your side or if there are breaking changes however,

**Comment by KennethEnevoldsen** [comment]
Yes will def. Add that during the week

**Comment by KennethEnevoldsen** [comment]
It should now have been added in #108. Enjoy!

**Comment by Dris101** [comment]
Many thanks Kenneth. That's great! I'm referencing the github repo in my ```pyproject.toml``` file with
```toml
spacy-wrap = {git = "https://github.com/KennethEnevoldsen/spacy-wrap.git", rev = "main"}
```
for the time being until you next push to PyPI and that's working fine for me now.
