### ISSUE TITLE
Custom model for NER

### ISSUE THREAD

**Issue by espoirMur** [KennethEnevoldsen/spacy-wrap#36]
Hello thanks you for setting up this .. 

The examples are amazing.

Is it possible to use this wrapper with a Named Entity Recognition model?

If that is the case, is it possible to add an example with a NER model from hugging face?

Following the example, I am trying to add this but it is not working, I do not  why may be I should go back and learn how spacy works.

```
import spacy
import spacy_wrap

nlp = spacy.blank("fr")

config = {
    "model": {
        "@architectures": "spacy-transformers.TransformerModel.v3",
        "name": "Jean-Baptiste/camembert-ner-with-dates",
        "tokenizer_config" : {"use_fast": False},
        "get_spans":  {"@span_getters": "spacy-transformers.doc_spans.v1"}
    }
}

transformer = nlp.add_pipe("ner", config=config)
```

**Comment by KennethEnevoldsen** [comment]
Hi @espoirMur, it seems like the model architecture you are using uses the `spacy-transformers.TransformerModel.v3` which is from spacy-transformers. If you want to use spacy-wrap you need to use the classification-transformer, however that currently only support classification models. 

It is however a plan to add NER model to this library as well, I would welcome a PR on this.

**Comment by LisaHoek** [comment]
Hi @espoirMur @KennethEnevoldsen, I was wondering, is anybody currently implementing this? It would be nice to have this in the near future, so I am curious whether I should get my hands dirty or whether I can expect this NER model anytime soon?

**Comment by KennethEnevoldsen** [comment]
Hi, @LisaHoek. Sorry for the late response was on holiday. I am currently not working on this feature, but I would very much welcome a pull request on the feature, and I would also help if solving any problems or kinks you might discover while tackling the problem.

**Comment by KennethEnevoldsen** [comment]
Hi @LisaHoek and @espoirMur, `space-wrap` now support NER and token classification as well 🍾

**Comment by espoirMur** [comment]
Thank you @KennethEnevoldsen 💪🏻
